### ISSUE TITLE
enable students to view grades

### ISSUE THREAD

**Issue by rKamindo** [rKamindo/Practice-Scrum-and-GitHub-Flow#1]
**User Story**
As a student, I want to be able to view assignment grades and class grades for all the courses I am enrolled in so that I can conveniently keep track of my grades, and so I don't have to ask my teacher what grade I received or what grade I have in a course.

**Detailed Description**
This is an essential and highly requested feature for our learning management system. We want to allow students to view their grades for assignments and courses they are enrolled in. For this story, we will create a read model for the student's view of grades, including assignments and grades as well as overall grades for a course. For the read model, we will need to write a database query. We will also need an API for fetching data which will be the read model of the student's view of grades. A student should only be able to view their grades alone. We also need to develop the UI for this, this will consist of a simple view with a list of assignments and the grade assigned, followed by grades by grade categories (exams, assignments, quizzes, etc.), and finally the total grade. For the categories we will show percentages as well as the actual points earned. This will also be done for the total grade, we will show points earned out of total as well as the percentage. See Figma mockup below.

**Task List**
- [x] Create query for read model for student's view of grades
- [x] Create read model for student's view of grades
- [x] Create API for fetching read model of student's grades, only a student can see their own grades
- [x] Create UI student's view of grades

**Acceptance Criteria**
- All published assignments/quizzes/tests/etc. in the course are displayed along with a grade if applicable
- Category grades are displayed (exams quizzes, assignments, homework, etc.)
- For categories and total grade, points earned out of total is shown, and a percentage is displayed
- Mobile-friendly

**Acceptance Tests**
- **Given**: I log in as a student
- **When**: I access the grades for a course I am enrolled in
- **Then**: I see a list of all my grades for assignments in the course
-------------------------------------
- **Given**: I log in as a student
- **When**: I try to access the grades for a course I am not enrolled in
- **Then**: I see an error page saying I do not have access to the course
-------------------------------------
- **Given**: I log in as a student
- **When**: I view the grade of a specific assignment
- **Then**: I see an accurate grade for a specific assignment
-------------------------------------
- **Given**: I log in as a student
- **When**: I view the category grades (assignments, quizzes, exams, etc.)
- **Then**: The sum of all grades in each category is accurate, as well as the percentage earned in the category
-------------------------------------
- **Given**: I log in on a mobile device as a student
- **When**: I view the grades for a course I am enrolled in
- **Then**: All the grades for all assignments are readable and in view, I can scroll to see all grades
